[build]
  publish = "."

[[headers]]
  for = "/projects.config.json"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/app.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/admin.js"
  [headers.values]
    Cache-Control = "no-cache"
